import { EncodeStream } from "@chr33s/pdf-restructure";
import cloneDeep from "clone";
import CFFTop from "../cff/./cff-top.js";
import type CFFFont from "../cff/cff-font.js";
import standardStrings from "../cff/cff-standard-strings.js";
import type CFFGlyph from "../glyph/cff-glyph.js";
import type { FontLike } from "../glyph/glyph.js";
import Path from "../glyph/path.js";
import Directory from "../tables/directory.js";
import Subset from "./subset.js";

const DEFAULT_EXTRA_TABLES = ["name", "OS/2", "post", "cmap", "vmtx", "VORG"] as const;
const EXCLUDED_TABLES = new Set(["fvar", "avar", "HVAR", "MVAR", "STAT"]);

// Limitations for PDF embedding: vertical metrics are copied only if vmtx/VORG exists; ToUnicode is
// generated by the PDF layer, not here; DSIG and variation tables are dropped.

const ENDCHAR = 14;
const RMOVETO = 21;
const RLINETO = 5;
const RRCURVETO = 8;

function encodeNumber(value: number): number[] {
  // Prefer integers when possible.
  if (Number.isInteger(value)) {
    const n = value | 0;
    if (n >= -107 && n <= 107) {
      return [n + 139];
    }

    if (n >= 108 && n <= 1131) {
      const v = n - 108;
      return [(v >> 8) + 247, v & 0xff];
    }

    if (n >= -1131 && n <= -108) {
      const v = -n - 108;
      return [(v >> 8) + 251, v & 0xff];
    }

    if (n >= -32768 && n <= 32767) {
      return [28, (n >> 8) & 0xff, n & 0xff];
    }
  }

  // Encode as a 16.16 fixed number (Type 2 real) using the 255 prefix.
  const fixed = Math.round(value * 65536);
  const view = new DataView(new ArrayBuffer(5));
  view.setUint8(0, 255);
  view.setInt32(1, fixed, false);
  return Array.from(new Uint8Array(view.buffer));
}

/**
 * Convert a Path into a Type 2 charstring (no subroutines, variation-free).
 * Width, if provided, is emitted first to match Type 2 charstring rules.
 */
export function encodePathToCharString(path: Path, width?: number | null): Uint8Array {
  const bytes: number[] = [];
  let x = 0;
  let y = 0;
  let contourStartX = 0;
  let contourStartY = 0;
  let hasContour = false;

  const emitNumber = (v: number) => {
    bytes.push(...encodeNumber(v));
  };

  const emitMoveTo = (nx: number, ny: number) => {
    const dx = nx - x;
    const dy = ny - y;
    emitNumber(dx);
    emitNumber(dy);
    bytes.push(RMOVETO);
    x = nx;
    y = ny;
    contourStartX = nx;
    contourStartY = ny;
    hasContour = true;
  };

  const emitLineTo = (nx: number, ny: number) => {
    const dx = nx - x;
    const dy = ny - y;
    emitNumber(dx);
    emitNumber(dy);
    bytes.push(RLINETO);
    x = nx;
    y = ny;
  };

  const emitCurveTo = (
    cp1x: number,
    cp1y: number,
    cp2x: number,
    cp2y: number,
    nx: number,
    ny: number,
  ) => {
    const dx1 = cp1x - x;
    const dy1 = cp1y - y;
    const dx2 = cp2x - cp1x;
    const dy2 = cp2y - cp1y;
    const dx3 = nx - cp2x;
    const dy3 = ny - cp2y;

    emitNumber(dx1);
    emitNumber(dy1);
    emitNumber(dx2);
    emitNumber(dy2);
    emitNumber(dx3);
    emitNumber(dy3);
    bytes.push(RRCURVETO);
    x = nx;
    y = ny;
  };

  if (typeof width === "number") {
    emitNumber(width);
  }

  for (const command of path.commands) {
    switch (command.command) {
      case "moveTo": {
        const [nx, ny] = command.args;
        emitMoveTo(nx, ny);
        break;
      }

      case "lineTo": {
        const [nx, ny] = command.args;
        emitLineTo(nx, ny);
        break;
      }

      case "quadraticCurveTo": {
        const [qp1x, qp1y, qx, qy] = command.args;
        // Convert quadratic to cubic using the same approach as Path.bbox.
        const cp1x = x + (2 / 3) * (qp1x - x);
        const cp1y = y + (2 / 3) * (qp1y - y);
        const cp2x = qx + (2 / 3) * (qp1x - qx);
        const cp2y = qy + (2 / 3) * (qp1y - qy);
        emitCurveTo(cp1x, cp1y, cp2x, cp2y, qx, qy);
        break;
      }

      case "bezierCurveTo": {
        const [cp1x, cp1y, cp2x, cp2y, nx, ny] = command.args;
        emitCurveTo(cp1x, cp1y, cp2x, cp2y, nx, ny);
        break;
      }

      case "closePath": {
        if (hasContour && (x !== contourStartX || y !== contourStartY)) {
          emitLineTo(contourStartX, contourStartY);
        }
        hasContour = false;
        break;
      }
    }
  }

  bytes.push(ENDCHAR);
  return new Uint8Array(bytes);
}

type UsageMap = Record<number, boolean>;

export default class CFF2Subset extends Subset {
  private readonly cff: CFFFont;
  private charstrings: Uint8Array[] = [];
  private gsubrs: Uint8Array[] = [];
  private strings?: string[];

  constructor(font: FontLike) {
    super(font);

    const cff = this.font.CFF2 as CFFFont | undefined;
    if (!cff) {
      throw new Error("Not a CFF2 Font");
    }

    this.cff = cff;
  }

  async subsetCharstrings(): Promise<void> {
    this.charstrings = [];
    const usedGsubrs: UsageMap = {};

    for (let gid of this.glyphs) {
      let glyph = this.font.getGlyph(gid) as CFFGlyph;
      const path = await glyph.getPath();
      const metrics = await glyph._getMetrics();
      this.charstrings.push(encodePathToCharString(path, metrics.advanceWidth));

      // Track used global subroutines for completeness (none emitted in baked charstrings).
      for (let subr in glyph._usedGsubrs) {
        usedGsubrs[Number(subr)] = true;
      }
    }

    // We bake outlines, so we do not carry subroutines forward; emit a single return subr.
    this.gsubrs = [new Uint8Array([11])];
  }

  addString(value: string | null): number | null {
    if (!value) {
      return null;
    }

    if (!this.strings) {
      this.strings = [];
    }

    this.strings.push(value);
    return standardStrings.length + this.strings.length - 1;
  }

  private buildCharset() {
    const glyphCount = this.charstrings.length;
    if (glyphCount <= 1) {
      return {
        version: 0,
        glyphs: [],
      };
    }

    // Build contiguous ranges from glyph index 1..N-1 (CID-keyed Identity).
    // Split into 255-sized chunks to stay within format limits when possible.
    const ranges: { first: number; nLeft: number }[] = [];
    let cursor = 1;
    const last = glyphCount - 1;
    while (cursor <= last) {
      const remaining = last - cursor;
      const chunk = Math.min(remaining, 255);
      ranges.push({ first: cursor, nLeft: chunk });
      cursor += chunk + 1;
    }

    return {
      version: glyphCount > 255 ? 2 : 1,
      ranges,
    };
  }

  private async buildTopDict(charset: Record<string, unknown>): Promise<Record<string, unknown>> {
    const topDict: Record<string, unknown> = {
      charset,
      Encoding: null,
      CharStrings: this.charstrings,
      Private: null,
    };

    for (let key of [
      "version",
      "Notice",
      "Copyright",
      "FullName",
      "FamilyName",
      "Weight",
      "PostScript",
      "BaseFontName",
      "FontName",
    ]) {
      // CFF2 fonts may not have strings here; add if present.
      topDict[key] = this.addString((this.cff as Record<string, any>)[key] ?? null);
    }

    topDict.ROS = [this.addString("Adobe"), this.addString("Identity"), 0];
    topDict.CIDCount = this.charstrings.length;

    // Create a single FDArray with a minimal Private dict; we bake outlines so Subrs is empty.
    const defaultWidthX = 0;
    const nominalWidthX = 0;
    const privateDict = { defaultWidthX, nominalWidthX, Subrs: [new Uint8Array([11])] };

    topDict.FDArray = [{ Private: privateDict }];
    topDict.FDSelect = {
      version: 3,
      nRanges: 1,
      ranges: [{ first: 0, fd: 0 }],
      sentinel: this.charstrings.length,
    };

    return topDict;
  }

  private buildCFFBuffer(topDict: Record<string, unknown>, subsetPsName: string) {
    const top = {
      version: 1,
      hdrSize: this.cff.hdrSize || 4,
      offSize: 4,
      header: this.cff.header || {},
      nameIndex: [subsetPsName],
      topDictIndex: [topDict],
      stringIndex: this.strings,
      globalSubrIndex: this.gsubrs,
    };

    const size = CFFTop.size(top);
    const paddedSize = Math.max(size * 2, size + 4096);
    const cffStream = new EncodeStream(new Uint8Array(paddedSize));
    CFFTop.encode(cffStream, top);
    return cffStream.buffer.subarray(0, cffStream.pos);
  }

  protected override async encode(stream: EncodeStream): Promise<void> {
    await this.subsetCharstrings();

    let glyphMetrics = [] as { advance: number; bearing: number }[];
    for (let gid of this.glyphs) {
      let glyph = this.font.getGlyph(gid) as CFFGlyph;
      let metrics = await glyph._getMetrics();
      glyphMetrics.push({
        advance: metrics.advanceWidth,
        bearing: metrics.leftBearing,
      });
    }

    let hmtx = {
      metrics: glyphMetrics,
      bearings: [] as number[],
    };

    let maxp = cloneDeep(this.font.maxp);
    maxp.numGlyphs = this.charstrings.length;

    let head = cloneDeep(this.font.head);
    let hhea = cloneDeep(this.font.hhea) as typeof this.font.hhea & {
      numberOfMetrics: number;
    };
    hhea.numberOfMetrics = hmtx.metrics.length;

    const charset = this.buildCharset();
    const subsetTag = makeSubsetTag(this.font.postscriptName ?? null);
    const subsetPsName = `${subsetTag}+${this.font.postscriptName || "CFF2Subset"}`;

    const topDict = await this.buildTopDict(charset);
    const cffTable = this.buildCFFBuffer(topDict, subsetPsName);

    const tables: Record<string, unknown> = {
      head,
      hhea,
      maxp,
      hmtx,
      "CFF ": cffTable,
    };

    const extras = new Set<string>([...DEFAULT_EXTRA_TABLES, ...this.tables]);
    for (const table of extras) {
      if (EXCLUDED_TABLES.has(table)) {
        continue;
      }

      const tableData = (this.font as Record<string, unknown>)[table];
      if (tableData != null) {
        let value = cloneDeep(tableData);
        if (table === "name") {
          value = rewriteNameTable(value, subsetPsName);
        }
        tables[table] = value;
      }
    }

    Directory.encode(stream, {
      tag: "OTTO",
      tables,
    });
  }
}

function makeSubsetTag(source: string | null | undefined): string {
  const text = source || "CFF2Subset";
  let hash = 0;
  for (let i = 0; i < text.length; i++) {
    hash = (hash * 31 + text.charCodeAt(i)) >>> 0;
  }

  const letters: string[] = [];
  for (let i = 0; i < 6; i++) {
    const code = 65 + (hash % 26);
    letters.push(String.fromCharCode(code));
    hash = Math.floor(hash / 26);
  }

  return letters.join("");
}

function rewriteNameTable(nameTable: any, subsetName: string) {
  if (!nameTable || !nameTable.records) {
    return nameTable;
  }

  const rewritten = cloneDeep(nameTable);
  const targets = ["postscriptName", "fullName", "fontFamily", "fontSubfamily"] as const;
  for (const key of targets) {
    const record = rewritten.records[key];
    if (!record) continue;
    for (const lang of Object.keys(record)) {
      record[lang] = subsetName;
    }
  }

  return rewritten;
}
