import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import peggy from "peggy";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const srcDir = path.join(projectRoot, "src");
const grammarPath = path.join(srcDir, "grammar.peg");
const outputPath = path.join(srcDir, "grammar.js");

async function buildGrammar(): Promise<void> {
  const grammar = await readFile(grammarPath, "utf8");

  // `output: "source"` makes peggy return the parser source, but its default
  // export types the result as `string | Parser`.
  const parserSource = peggy.generate(grammar, {
    cache: true,
    output: "source",
    format: "es",
  }) as string;

  const banner = [
    "// @ts-nocheck",
    "// This file is generated by scripts/build-grammar.ts. Do not edit by hand.\n",
  ].join("\n");
  await writeFile(outputPath, `${banner}${parserSource}`);
  console.log(`Generated ${path.relative(projectRoot, outputPath)}`);
}

buildGrammar().catch((error) => {
  console.error("Failed to build grammar:", error);
  process.exitCode = 1;
});
