name: CI

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: "package.json"
      - run: npm ci --include=dev
      - run: npm run workspace build
      - run: npm run check
      - run: npm run workspace test
      - run: npm run docs
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  wiki:
    name: Wiki
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/checkout@v5
        with:
          repository: ${{github.repository}}.wiki
          path: ${{github.repository}}.wiki
      - run: |
          set -e
          cd $GITHUB_WORKSPACE/${{github.repository}}.wiki
          cp -r $GITHUB_WORKSPACE/docs/* .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "update: sync docs" && git push

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      id-token: write
    strategy:
      matrix:
        package: [common, codepoints, dfa, restructure, standard-fonts, unicode-trie, unicode-properties, upng, fontkit, pdf]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: "package.json"
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --prefix packages/${{ matrix.package }} --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/github-script@v7
        with:
          script: |
            const tag_name = context.ref;
            const name = tag_name.replace(/^refs\/tags\/v/, '');
            const version = name.split("/").at(-1);
            const prerelease = version.startsWith("0.") || version.includes("-");
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner,
              repo,
            });
            const latestReleaseTagName = latestRelease.tag_name;
            const latestReleaseVersion = latestReleaseTagName.split("/").at(-1);
            const body = `changes: [${latestReleaseVersion}...${version}](https://github.com/${owner}/${repo}/compare/${latestReleaseTagName}...${tag_name})`;

            await github.rest.repos.createRelease({
              body,
              name,
              owner,
              prerelease,
              repo,
              tag_name,
            });

